# 다차원 배열의 계산

In [7]:
import numpy as np

A = np.array([1,2,3,4])
np.ndim(A)
B = np.array([[1,2],[3,4],[5,6]])
B.shape

(3, 2)

## 행렬의 곱

In [15]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

# 행렬 곱
np.dot(A,B)

# 원소별 곱
print(A * B)

[[ 5 12]
 [21 32]]


In [10]:
import numpy as np
vector1 = np.array([[1,2,3],[4,5,6]])
print(np.shape(vector1))
matrix1 = np.array([[1,4],[2,5],[3,6]])
print(np.shape(matrix1))
print(vector1)

result = vector1.dot(matrix1)
print(result)
np.shape(result)

(2, 3)
(3, 2)
[[1 2 3]
 [4 5 6]]
[[14 32]
 [32 77]]


(2, 2)